steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/llmops-495904/rag-repo/rag-api:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/llmops-495904/rag-repo/rag-api:latest
      - .

images:
  - us-central1-docker.pkg.dev/llmops-495904/rag-repo/rag-api:$COMMIT_SHA
  - us-central1-docker.pkg.dev/llmops-495904/rag-repo/rag-api:latest

options:
  logging: LEGACY
